services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DB: ${MYSQLDATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
      MYSQL_PORT: ${MYSQLPORT}
    ports:
      - 33061:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}
      PMA_HOST: mysql
    ports:
      - 8080:80
